### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by malik672** [Perelyn-sama/yul_by_example#34]
1.you don't need to check for underflow and overflow, since it's version 0.8.17
2.add natspec documentation
3.caching value in some part of code will reduce gas instead of calling the opcode twice we can simply store the value in the stack and fetch it back for later use, e.g `    // Function to increment count by 1
    function inc() public {
        assembly {
            // Assign count variable slot to countSlot.
            let countSlot := count.slot

            // We update the value at the `count` slot by incrementing the
            // current value at the slot by 1, then calling an sstore() to overwrite the
            // value at slot 0.
            // However, this doesn't check for overflows and underflows, so we must make sure that
            // we do not go beyond the limit for our type maximum before making the update.
            // We are working with uint256, so the max is 0x("ff" * 32).
            if eq(sload(countSlot), 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff) { revert(0, 0) }
            sstore(countSlot, add(sload(countSlot), 1))
        }
    }
`
here we can simply reduce the gas value by doing something like this `   function inc() public {
        assembly {
            // Assign count variable slot to countSlot.
            let countSlot := count.slot

            // We update the value at the `count` slot by incrementing the
            // current value at the slot by 1, then calling an sstore() to overwrite the
            // value at slot 0.
            // However, this doesn't check for overflows and underflows, so we must make sure that
            // we do not go beyond the limit for our type maximum before making the update.
            // We are working with uint256, so the max is 0x("ff" * 32).
            let cachedValue := sload(countSlot)
            if eq(cachedValue, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff) { revert(0, 0) }
            sstore(countSlot, add(cachedValue, 1))
        }
    }
`
4. in the loop contract we don't need to initialize the value to zero they are already zero by default

**Comment by 0xfps** [comment]
**Can you please specify which files which number points to?**

1. In Yul blocks, there are no checks for under and overflows.
2. We try to keep it simple for now, documentations for each can be seen in the `docs/` directory, (it is still WIP).
3. Thank you for that info, it is being worked on.
4. Duly noted.

PS: Your inputs are highly appreciated, I forgot to make a new "optimization" issue that includes taking a close look at everything we have done for this section and making them better. It has been added.

**Comment by malik672** [comment]
I think they are checks for underflow and overflow in yul blocks, try it out, the compiler should throw an error for underflow or overflow
