### ISSUE TITLE
Regarding Comments in Structs.sol

### ISSUE THREAD

**Issue by Aryan9592** [Perelyn-sama/yul_by_example#66]
Hey @0xfps,

while going through Structs.sol, the file looked like this:

![Screenshot (68)](https://github.com/Perelyn-sama/yul_by_example/assets/88618913/954f9e9b-33cd-46cc-8680-ec26001ee898)

That part is not commented and gonna be hard for new users to understand like what's going on here..What If I add comments in here?

![Screenshot (69)](https://github.com/Perelyn-sama/yul_by_example/assets/88618913/899c9a78-f63a-4ac3-aaac-bdcd8f92fa62)

Thanks!

**Comment by 0xfps** [comment]
Sure, you can do that. Thanks!

**Comment by Aryan9592** [comment]
Well, time for another PR then!
